### ISSUE TITLE
Create a minimal example

### ISSUE THREAD

**Issue by schell** [TheHellBox/openhmd-rs#2]
First, thank you for this library! It would be very nice to have a minimal example in the readme - something like spinning triangles or cubes.

**Comment by TheHellBox** [comment]
For examples, you can look at my OpenHMD-Chat code. Mostly it's very simple, get eye matrix, apply it to the camera view model and that it. https://github.com/TheHellBox/OpenHMD-Chat/blob/master/src/render/mod.rs#L215

**Comment by schell** [comment]
Great! Thank you.
